#!/usr/bin/python3
"""
Module 6-max_integer
find the max integer in a list
"""


def max_integer(list=[]):
    """
    Search and Return the max integer in a list
    """
    if len(list) == 0:
        return None
    max_num = list[0]
    i = 1
    while i < len(list):
        if list[i] > max_num:
            max_num = list[i]
        i += 1
    return max_num